[workspace]
members = [
  "common_collections",
  "error_handling",
  "generics",
  "unit_test/adder",
  "minigrep",
  "functional",
  "cargo_detail",
  "smart_pointer",
  "multi_threads",
  "oop",
  "pattern_matching",
  "macros",
  "hello_macro",
  "hello_macro_derive",
]
